# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: github-push-transformation-trigger
spec:
  broker: transformation-demo
  filter:
    attributes:
      type: dev.knative.source.github.push
  subscriber:
    ref:
      apiVersion: flow.triggermesh.io/v1alpha1
      kind: Transformation
      name: github-push-transformation

---

apiVersion: flow.triggermesh.io/v1alpha1
kind: Transformation
metadata:
  name: github-push-transformation
spec:
  context:
  - operation: store
    paths:
    - key: $ceType
      value: type

  - operation: add
    paths:
    - key: type
      value: io.triggermesh.transformation.github

  data:
  - operation: store
    paths:
    - key: $repository
      value: repository.name
    - key: $message
      value: head_commit.message
    - key: $author
      value: head_commit.author.username

  - operation: delete
    paths:
    - key:

  - operation: add
    paths:
    - key: type
      value: $ceType
    - key: object
      value: $author
    - key: subject
      value: $repository
    - key: verb
      value: $message

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: github-issue-transformation-trigger
spec:
  broker: transformation-demo
  filter:
    attributes:
      type: dev.knative.source.github.issues
  subscriber:
    ref:
      apiVersion: flow.triggermesh.io/v1alpha1
      kind: Transformation
      name: github-issue-transformation

---

apiVersion: flow.triggermesh.io/v1alpha1
kind: Transformation
metadata:
  name: github-issue-transformation
spec:
  context:
  - operation: store
    paths:
    - key: $ceType
      value: type

  - operation: add
    paths:
    - key: type
      value: io.triggermesh.transformation.github

  data:
  - operation: store
    paths:
    - key: $action
      value: action
    - key: $repository
      value: repository.name
    - key: $title
      value: issue.title
    - key: $author
      value: issue.user.login

  - operation: delete
    paths:
    - key:

  - operation: add
    paths:
    - key: type
      value: $ceType
    - key: object
      value: $author
    - key: subject
      value: $repository
    - key: verb
      value: $action issue "$title"
