# Copyright 2022 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Recieve a CSNF event and transform it into an Azure Sentinel event
apiVersion: flow.triggermesh.io/v1alpha1
kind: Transformation
metadata:
  name: csnf-sentinel
spec:
  sink:
    ref:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: Target
      name: hello-sentinel
  context:
  - operation: add
    paths:
    - key: type
      value: io.triggermesh.azure.sentinel.create.incident
  data:
  - operation: store
    paths:
    - key: $name
      value: event.name
    - key: $etag
      value: event.guid
    - key: $title
      value: event.name
    - key: $incidentID
      value: event.resource.identifier
    - key: $description
      value: event.shortDescription
  - operation: delete
    paths:
    - key:
  - operation: add
    paths:
    - key: etag
      value: $etag
    - key: properties.providerIncidentId
      value: $incidentID
    - key: properties.status
      value: new
    - key: properties.severity
      value: high
    - key: properties.title
      value: $title
    - key: properties.description
      value: $description
    - key: properties.owner.assignedTo
      value: bob
