# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: targets.triggermesh.io/v1alpha1
kind: HasuraTarget
metadata:
  name: hasuratarget

spec:
  endpoint: 'http://hasura.example.com:8080'  # Target hasura instance
  admin:
    secretKeyRef:
      name: hasuratargetadminsecret
      key: token
  queries:
    MyQuery: "query MyQuery($person_id: Int) { foo(where: {id: {_eq: $person_id}} ) { id name } }"

---
apiVersion: targets.triggermesh.io/v1alpha1
kind: HasuraTarget
metadata:
  name: hasuratargetjwt

spec:
  endpoint: 'http://hasura.example.com:8080'  # Target hasura instance
  # This is optional and more useful with a trigger specific jwt token or if the endpoint uses a webhook.
  defaultRole: reader
  jwt:
    secretKeyRef:
      name: hasuratargetjwtsecret
      key: token
