# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: mynamespace
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display

---

apiVersion: targets.triggermesh.io/v1alpha1
kind: InfraTarget
metadata:
  name: ex1
  namespace: mynamespace
spec:
  script:
    code: |-

      // add extra field
      input.data.extra = "this is an extra field";

      // use javascript to add a value to a new field
      input.data.date =  Date().toString();

      // set a new type to avoid loops
      input.type = "infra.type";

      // add a header extension
      input.myextension = "by-triggermesh";

      // replace existing value
      input.data["sensible-info"] = "REDACTED";

      // do some string work joining two input fields into one
      input.data.fullname = input.data["name"] + " " + input.data["lastname"];
      delete input.data["name"];
      delete input.data["lastname"];

      return input

---

apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: infra-ex1
  namespace: mynamespace

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: pinginfra
  namespace: mynamespace
spec:
  broker: infra-ex1
  filter:
    attributes:
      type: dev.knative.sources.ping
  subscriber:
    ref:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: InfraTarget
      name: ex1

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: infraeventdisplay
  namespace: mynamespace
spec:
  broker: infra-ex1
  filter:
    attributes:
      type: infra.type
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display

---

apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: minute-request
  namespace: mynamespace
spec:
  jsonData: '{"hello":"world","sensible-info":"sensible-value", "name":"Ignatius", "lastname":"Reilly"}'
  schedule: '*/1 * * * *'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: infra-ex1
