# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: targets.triggermesh.io/v1alpha1
kind: LogzMetricsTarget
metadata:
  name: logzmetrics
spec:
  connection:
    listenerURL: http://listener.logz.io:8052
    token:
      secretKeyRef:
        name: logzmetrics
        key: token
  instruments:
  - name: total_requests
    instrument: Counter
    number: Int64
    description: total requests
  - name: quacking_ducks
    instrument: UpDownCounter
    number: Int64
    description: number of quacking ducks observed
  - name: request_duration_ms
    instrument: Histogram
    number: Float64
    description: request duration in milliseconds
